### ISSUE TITLE
Global navigation font

### ISSUE THREAD

**Issue by maydeyn** [developerBME/street_care_webapp#3]
<img width="650" alt="image" src="https://github.com/developerBME/street_care_webapp/assets/37945190/22a67367-a2af-44a1-9420-5ff529150cb3">

**The font and font sizes of desktop navigation bar needs to be updated**

"Street Care" spec
```
color: var(--White, #FFF);
/* Headline Medium */
font-family: Bricolage Grotesque;
font-size: 28px;
font-style: normal;
font-weight: 500;
line-height: 36px; /* 128.571% */
```

Nav items spec
```
/* Label Large */
font-family: Inter;
font-size: 18px;
font-style: normal;
font-weight: 600;
line-height: 24px; /* 133.333% */
letter-spacing: -0.18px;
```

**Comment by niravpatell23** [comment]
Current "Street Care" spec

color: var(--White, #FFF);
/* Headline Medium */
```
font-family: Bricolage Grotesque;
font-size: 24px; (Change)
font-style: normal;
font-weight: 500;
line-height: 36px; /* 128.571% */

```

Current Nav items spec

/* Label Large */
```
[font-family: Inter;
font-size: 14px;  (Change)
font-style: normal;
font-weight: 500; (Change)
line-height: 24px; /* 133.333% */
letter-spacing: -0.18px;]
```

We had a little trouble getting your design to fit perfectly on screens with a 1920x1080 resolution. So, we made the font sizes a bit smaller to make it match what's in Figma.
I will make the changes as per the design so that you can have a look too.
